// Music resources to use with the music system
const music = {
  // List of sources
  sources: [
    "applemusic",
    "bandcamp",
    "deezer",
    "flowery-tts",
    "jiosaavn",
    "qobuz",
    "soundcloud",
    "spotify",
    "tidal",
    "yandexmusic",
    "vkmusic",
    "youtube",
    "youtubemusic",
  ],
  /**
   * * Available Search Platforms
   * ! Don't try to change this unless you know what you are doing.
   * @type {import("lavalink-client").SearchPlatform[]}
   */
  searchPlatforms: [
    "http",
    "https",
    "link",
    "local",
    "uri",
    "am",
    "amsearch",
    "apple",
    "apple music",
    "applemusic",
    "music apple",
    "bc",
    "bcsearch",
    "bandcamp",
    "dz",
    "dzsearch",
    "deezer",
    "tts",
    "ftts",
    "flowery",
    "flowerytts",
    "flowery.tts",
    "js",
    "jssearch",
    "jiosaavn",
    "qbsearch",
    "qobuz",
    "sc",
    "scsearch",
    "soundcloud",
    "sp",
    "spsearch",
    "spotify",
    "spotifycom",
    "spotify.com",
    "td",
    "tdsearch",
    "tidal",
    "tidal music",
    "ymsearch",
    "yandex",
    "yandexmusic",
    "yandex music",
    "yt",
    "ytsearch",
    "youtube",
    "ytm",
    "ytmsearch",
    "youtubemusic",
    "youtube music",
    "music youtube",
    "vk",
    "vksearch",
    "vkmusic",
    "vk music",
  ],
};

module.exports = { music };
