server: # REST and WS server
  port: 3712 # The port that the server listens on
  address: 0.0.0.0
  http2:
    enabled: false # Whether to enable HTTP/2 support
    address: 0.0.0.0
  compression:
    enabled: true # Whether to enable gzip compression
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false # disable youtube on lavalink to use youtube-source
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      nico: true
      http: false # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
      local: true
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 600 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 7000 # How many milliseconds of audio to keep buffered
    httpRequestTimeout: 20000 # The timeout for HTTP requests made by Lavaplayer, in milliseconds.
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: HIGH # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 15000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 3 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    # ratelimit:
    #   ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
    #   excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
    #   strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
    #   searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
    #   retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    # youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
    #   email: "your account mail" # Email of Google account
    #   password: "your account password" # Password of Google account
    # httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
    #   proxyHost: "" # Hostname of the proxy, (ip or domain)
    #   proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
    #   proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
    #   proxyPassword: "" # Password for basic authentication
    timeouts:
      connectTimeoutMs: 10000
      connectionRequestTimeoutMs: 10000
      socketTimeoutMs: 10000
  pluginsDir: "./plugins"
  plugins:
    - dependency: "com.github.devoxin:lavadspx-plugin:0.0.5" # https://github.com/devoxin/LavaDSPX-Plugin
      repository: "https://jitpack.io"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0" # https://github.com/lavalink-devs/youtube-source
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1" # LavaSrc - https://github.com/topi314/LavaSrc
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0" # https://github.com/topi314/LavaSearch
    # - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.1" # https://github.com/DuncteBot/skybot-lavalink-plugin
    - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1" # https://github.com/topi314/SponsorBlock-Plugin
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.1.0" # https://github.com/topi314/LavaLyrics
    - dependency: "me.duncte123:java-lyrics-plugin:1.6.6" # https://github.com/DuncteBot/java-timed-lyrics
plugins:
  lyrics:
    countryCode: de # country code for resolving isrc tracks
    geniusApiKey: "<api_key>" # leave this out to disable genius searching. Get your api key (Client Access Token) from https://genius.com/api-clients
  lavalyrics:
    sources:
      - genius
      - spotify
      - youtube
      # - deezer
      # - yandexMusic
  sponsorblock:
    enabled: true
  youtube:
    enabled: true
    # To simplify signature deciphering, you can use a remote cipher server like yt-cipher, a lightweight Deno server with a REST API. More details are available at https://github.com/kikkia/yt-cipher
    remoteCipher:
      url: "https://cipher.kikkia.dev/" # The base URL of your remote cipher server.
      # password: "it_works" # The password to authenticate with your remote cipher server.
      retries: 3
      retryDelay: 500
      userAgent: "Hopeless-Test-Server" # Optional user-agent header, used for metrics on the backend.
    oauth:
      enabled: false
      # refreshToken: "Insert your refresh token here" # For more details, please refer to https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-oauth-tokens
    # pot: for more detals please refer to https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-a-potoken
    #     token: "<intsert>"
    #     visitorData: "<insert>"
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # For more details about client setup, refer to https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients
    clients:
      - "ANDROID_MUSIC"
      - "ANDROID_VR"
      - "MUSIC"
      - "WEB"
      - "WEBEMBEDDED"
      - "MWEB"
      - "IOS"
      - "TVHTML5_SIMPLY"
    # This secure your lavalink is working and playing music if you used this two things below.
    ANDROID_MUSIC:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: true
    ANDROID_VR:
      playlistLoading: true
      videoLoading: true
      searching: true
      playback: true
    MUSIC:
      playlistLoading: false
      videoLoading: false
      searching: true
      playback: false
    WEB:
      playlistLoading: true
      videoLoading: true
      searching: true
      playback: true
    MWEB:
      playlistLoading: true
      videoLoading: true
      searching: true
      playback: true
    WEBEMBEDDED:
      playlistLoading: false
      videoLoading: true
      searching: false
      playback: true
    IOS:
      playlistLoading: true
      videoLoading: true
      searching: true
      playback: true
    TVHTML5_SIMPLY:
      playlistLoading: false
      videoLoading: true
      searching: true
      playback: true
  lavasrc:
    providers: # Custom providers for track loading. This is the default
      - 'ytsearch:"%ISRC%"'
      - "dzisrc:%ISRC%"
      - "ytsearch:%QUERY%"
      - "dzsearch:%QUERY%"
      - "scsearch:%QUERY%"
      - "tdsearch:%QUERY%"
      #  you can add multiple other fallback sources here
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false # reason need to be in a particular country/region
      flowerytts: true
      youtube: true
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
    lyrics-sources:
      spotify: true
      deezer: false
      youtube: true
      yandexmusic: false
      vkmusic: false
      lrcLib: true
    spotify:
      clientId: "<client_id>" # your spotify client id
      clientSecret: "<client_secret>" # your spotify client secret
      spDc: "<sp_dc_cookie>" # the sp dc cookie used for accessing the spotify lyrics api
      preferAnonymousToken: false # Use this to generate and cache anonymous Spotify access tokens from your own endpoint, as Spotify recently updated their implementation.
      customTokenEndpoint: "http://localhost:8080/api/token" # For more details, please refer to https://github.com/topi314/spotify-tokener
      resolveArtistsInSearch: true # Whether to resolve artists in track search results (can be slow)
      albumLoadLimit: 2 # The number of pages at 50 tracks each
      countryCode: "US"
      playlistLoadLimit: 3 # The number of pages at 100 tracks each
      localFiles: true # Enable local files support with Spotify playlists. Please note `uri` & `isrc` will be `null` & `identifier` will be `"local"`
      useWebAPI: true
      audioQuality: HIGH
    applemusic:
      countryCode: "US"
      mediaAPIToken: "<media_api_token>" # apple music api token
      # or specify an apple music key
      keyID: "<key_id>" # your key id
      teamID: "<team_id>" # your team id
      musicKitKey: |
        -----BEGIN PRIVATE KEY-----
        <your_key>
        -----END PRIVATE KEY-----
      playlistLoadLimit: 3 # The number of pages at 300 tracks each
      albumLoadLimit: 3 # The number of pages at 300 tracks each
    deezer:
      masterDecryptionKey: "<key>"
      arl: "<arl_cookie>" # the arl cookie used for accessing the deezer api
      formats: ["MP3_128", "MP3_64"] # the formats you want to use for the deezer tracks. "FLAC", "MP3_320", "MP3_256" & "AAC_64" are only available for premium users and require a valid arl
    yandexmusic:
      accessToken: "<access_token>" # the token used for accessing the yandex music api. See https://github.com/topi314/LavaSrc#yandex-music
      playlistLoadLimit: 1 # The number of pages at 100 tracks each
      albumLoadLimit: 1 # The number of pages at 50 tracks each
      artistLoadLimit: 1 # The number of pages at 10 tracks each
      # proxy: # To avoid YandexMusic region blocking
      #     url: "https://example.org" # The HTTP proxy to use
      #     username: "my-bot" # Optional username to authenticate with the proxy
      #     password: "youshallpass" # Optional password to authenticate with the proxy
    flowerytts:
      voice: "Alexander" # (case-sensitive) get default voice from here https://api.flowery.pw/v1/tts/voices
      translate: false # whether to translate the text to the native language of voice
      silence: 0 # the silence parameter is in milliseconds. Range is 0 to 10000. The default is 0.
      speed: 1.0 # the speed parameter is a float between 0.5 and 10. The default is 1.0. (0.5 is half speed, 2.0 is double speed, etc.)
      audioFormat: "mp3" # supported formats are: mp3, ogg_opus, ogg_vorbis, aac, wav, and flac. Default format is mp3
    youtube:
      countryCode: "US"
      language: "en" # the language code you want to use for searching & lyrics.
    vkmusic:
      userToken: "<user_token>" # This token is needed for authorization in the api. Guide: https://github.com/topi314/LavaSrc#vk-music
      playlistLoadLimit: 1 # The number of pages at 50 tracks each
      artistLoadLimit: 1 # The number of pages at 10 tracks each
      recommendationsLoadLimit: 10 # Number of tracks
      # proxy: # Cause VK Music only available in russia.
      #      url: "https://example.org" # The HTTP proxy to use
      #      username: "my-bot" # Optional username to authenticate with the proxy
      #      password: "youshallpass" # Optional password to authenticate with the proxy
    tidal:
      countryCode: "US"
      searchLimit: 6 # How many search results should be returned
      token: "<your_tidal_token>" # the token used for accessing the tidal api. See https://github.com/topi314/LavaSrc#tidal
    qobuz:
      userOauthToken: "<your_user_oauth_token>" # This token is needed for authorization in the api. Guide: https://github.com/topi314/LavaSrc#qobuz
      # appId : "<app_id>" # optional (Only pass it when you are using an old userOauthToken)
      # appSecret : "<app_secret>" # optional (Only pass it when you are using an old userOauthToken)
    ytdlp:
      path: "yt-dlp" # the path to the yt-dlp executable.
      searchLimit: 10 # How many search results should be returned
      # customLoadArgs: ["-q", "--no-warnings", "--flat-playlist", "--skip-download", "-J"] # Custom arguments to pass to yt-dlp
      # customPlaybackArgs: ["-q", "--no-warnings", "-f", "bestaudio", "-J"] # Custom arguments for yt-dlp
    jiosaavn:
      decryption: # The decryption configuration for the JioSaavn tracks
        secretKey: "<secret_key>" # The required secret key used for decryption (Find your own secret key)
        # algorithm: "DES" # The algorithm used for decryption (Default "DES")
        # transformation: "DES/ECB/PKCS5Padding" # The transformation used for decryption (Default "DES/ECB/PKCS5Padding")
      # proxy: # To avoid JioSaavn region blocking.
      #     url: "https://example.org" # The HTTP proxy to use
      #     username: "my-bot" # Optional username to authenticate with the proxy
      #     password: "youshallpass" # Optional password to authenticate with the proxy
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
logging:
  path: ./logs/
  file:
    max-history: 5
    max-size: 10MB
  level:
    root: INFO # Set this to DEBUG to enable more detailed logging. Please note that this will likely spam your console.
    lavalink: INFO # Set this to DEBUG to enable more detailed logging from Lavalink.
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: true
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
